fwx-objs := fwx_main.o fwx_utils.o  regexp.o k_json.o  fwx_log.o fwx_client.o fwx_client_fs.o 
fwx-objs += fwx_conntrack.o  fwx_mac.o fwx_config.o fwx_mac_filter.o 
fwx-objs += fwx_app_filter.o
obj-m += fwx.o

ccflags-y += -Wno-declaration-after-statement -Wno-strict-prototypes -Wno-unused-variable -Wno-implicit-fallthrough -Wno-missing-braces -Wno-parentheses -Wno-format -Wno-missing-prototypes -Wno-missing-declarations -Wno-misleading-indentation -Wno-frame-larger-than
